### ISSUE TITLE
有几个疑问麻烦作者老哥解答一下

### ISSUE THREAD

**Issue by MisterGlasses** [BlueskyClouds/iQIYI-DailyBonus#1]
第一个就是填入用qx等工具抓的的cookie，脚本可以正常运行吗？
第二个是电脑版的cookie有效期可以长达三个月，qx抓到的cookie有效期大约是多久？
第三个是可以支持下bark推送吗？可以省得进微信查看推送内容。bark推送lxk0301老哥的GitHub库中有用到，感觉效果比server酱要好。
第四个是脚本log中显示 爱奇艺-抽奖明细: 未中奖 🎉 (1) ，为什么只抽一次奖？不是有三次机会吗？

**Comment by BlueskyClouds** [comment]
1 只需要authcookie   就相当于你cookie中的P00001值即可，其他的不需要，
2 不清楚过期时间，电脑端的可以看见过期时间，
3 应该是可以的，我有空看看。
4 因为你当天已经签到过了，所以第二次只跑了一遍，第一次签到是会抽3次的

**Comment by MisterGlasses** [comment]
> 1 只需要authcookie 就相当于你cookie中的P00001值即可，其他的不需要，
> 2 不清楚过期时间，电脑端的可以看见过期时间，
> 3 应该是可以的，我有空看看。
> 4 因为你当天已经签到过了，所以第二次只跑了一遍，第一次签到是会抽3次的

请问如何查看第2条所说的到期时间呢

**Comment by BlueskyClouds** [comment]
![QQ截图20201009160322](https://user-images.githubusercontent.com/39831773/95558598-110eb900-0a49-11eb-8e33-57e9089a26d3.jpg)

**Comment by BlueskyClouds** [comment]
bark 我目前没有可测试的ios   而且需要自建服务端  暂时不考虑.

**Comment by MisterGlasses** [comment]
> bark 我目前没有可测试的ios 而且需要自建服务端 暂时不考虑.

老哥bark不需要自建 可以直接使用如需测试 我可以协助

**Comment by MisterGlasses** [comment]
`https://github.com/lxk0301/scripts `lxk大佬项目中的脚本均用到了bark 可以参考一下

**Comment by BlueskyClouds** [comment]
那你加我吧，Q1471223507
